query GetAllJobItems {
  JobItems(resolve_links: "url") {
    items {
      content {
        title
        projects {
          content
        }
        end
        content
        beginning
        _uid
      }
      slug
    }
  }
}
